In [1]:
import pickle
import numpy as np
import torch
import pandas as pd
import os

In [2]:
os.getcwd()

'/home/tduricic/Development/workspace/elliot/external/models/graphrec'

In [30]:
social_adj_lists

defaultdict(set,
            {0: {1, 2},
             1: {0},
             2: {0},
             3: {4, 44, 84, 85, 201},
             4: {3, 44, 84, 85, 210, 267},
             5: {6},
             6: {5, 558},
             7: {8, 9, 10},
             8: {7},
             9: {7, 56, 266, 342, 382, 402, 696},
             10: {7},
             11: {12, 13},
             12: {11},
             13: {11,
              23,
              24,
              25,
              27,
              28,
              29,
              35,
              37,
              38,
              40,
              42,
              43,
              44,
              56,
              58,
              84,
              86,
              88,
              97,
              119,
              124,
              182,
              190,
              213,
              214,
              228,
              234,
              243,
              255,
              263,
              280,
              283,
       

In [2]:
dir_data = './data/toy_dataset'

path_data = dir_data + ".pickle"
data_file = open(path_data, 'rb')
history_u_lists, history_ur_lists, history_v_lists, history_vr_lists, train_u, train_v, train_r, test_u, test_v, test_r, social_adj_lists, ratings_list = pickle.load(data_file)

NameError: name 'pickle' is not defined

In [26]:
print(len(train_u))
print(len(test_u))

counter = 0
for u in history_u_lists:
    for i in history_u_lists[u]:
        counter += 1
print(counter)

14091
3733
14091


In [15]:
# items rated by user 681 with an added 0 in the beginning
history_u_lists[681]

[0,
 156,
 267,
 24,
 255,
 102,
 47,
 130,
 131,
 78,
 61,
 62,
 166,
 45,
 32,
 122,
 661,
 33,
 69,
 902,
 124,
 31,
 41,
 74,
 21,
 144,
 914,
 60,
 564,
 22,
 13,
 55,
 145,
 1051,
 330]

In [20]:
with open('./data/ratings.tsv', 'w') as the_file:
    for user_id in history_u_lists:
        for item_idx in range(len(history_u_lists[user_id])):
            the_file.write(f'{user_id}\t{history_u_lists[user_id][item_idx]}\t{history_ur_lists[user_id][item_idx]}\n')

In [21]:
social_edges = []

for u in social_adj_lists:
        for v in social_adj_lists[u]:
            if (u,v) not in social_edges and (v,u) not in social_edges:
                social_edges.append((u,v))

with open('./data/social_connections.tsv', 'w') as the_file:
    for social_edge in social_edges:
        the_file.write(f'{social_edge[0]}\t{social_edge[1]}\t1\n')

In [19]:
type(social_adj_lists[0])

set

In [28]:
# item ratings by user 681 with an added 0 in the beginning
history_ur_lists[681]

[0,
 2,
 2,
 3,
 2,
 2,
 5,
 5,
 3,
 2,
 5,
 2,
 2,
 2,
 2,
 5,
 4,
 4,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 4,
 2,
 4,
 2,
 5,
 5,
 2,
 0,
 5,
 5]

In [5]:
# users rated item 0
history_v_lists[0]

[681,
 48,
 577,
 143,
 615,
 374,
 285,
 19,
 379,
 369,
 55,
 638,
 413,
 213,
 146,
 375,
 159,
 346,
 66,
 587,
 620,
 203,
 113,
 15,
 234,
 636,
 359,
 76,
 486,
 78,
 320,
 70,
 598,
 321,
 650,
 676,
 226,
 105,
 641,
 252,
 350,
 131,
 611,
 454,
 590,
 570,
 703,
 405,
 227,
 11,
 503,
 274,
 429,
 694,
 126,
 255,
 680,
 52,
 51,
 258,
 300,
 151,
 1,
 699,
 568,
 585,
 516,
 632,
 551,
 425,
 659,
 343,
 325,
 646,
 393,
 479,
 200,
 138,
 404,
 483,
 286,
 164,
 336,
 648,
 242,
 97,
 639,
 124,
 522,
 365,
 93,
 603,
 525,
 118,
 536,
 700,
 64,
 599,
 484,
 669,
 640,
 210,
 179,
 693,
 186,
 439,
 560,
 622,
 34,
 464,
 233,
 212,
 409,
 552,
 318,
 276,
 199,
 282,
 366,
 675,
 182,
 610,
 206,
 170,
 77,
 4,
 564,
 664,
 123,
 204,
 496,
 453,
 256,
 462,
 230,
 549,
 683,
 471,
 673,
 49,
 82,
 408,
 98,
 695,
 13,
 289,
 487,
 83,
 376,
 90,
 163,
 392,
 645,
 401,
 508,
 121,
 192,
 175,
 500,
 372,
 628,
 135,
 556,
 674,
 235,
 475,
 33,
 668,
 340,
 644,
 337,
 

In [30]:
# user ratings on item 0
history_vr_lists[0]

[0,
 2,
 4,
 6,
 0,
 5,
 2,
 3,
 3,
 2,
 2,
 2,
 7,
 1,
 5,
 4,
 6,
 4,
 0,
 5,
 1,
 1,
 3,
 5,
 5,
 4,
 4,
 4,
 2,
 4,
 3,
 2,
 1,
 3,
 0,
 2,
 6,
 4,
 6,
 3,
 5,
 0,
 3,
 5,
 0,
 4,
 3,
 0,
 6,
 2,
 3,
 7,
 5,
 3,
 6,
 3,
 4,
 6,
 0,
 2,
 7,
 4,
 4,
 2,
 0,
 2,
 3,
 4,
 6,
 2,
 4,
 6,
 5,
 4,
 2,
 3,
 0,
 4,
 4,
 5,
 6,
 0,
 2,
 0,
 3,
 2,
 2,
 4,
 4,
 3,
 3,
 2,
 0,
 4,
 0,
 4,
 2,
 1,
 2,
 3,
 5,
 4,
 6,
 3,
 4,
 2,
 3,
 6,
 6,
 3,
 6,
 2,
 2,
 3,
 5,
 1,
 0,
 3,
 3,
 1,
 3,
 0,
 2,
 2,
 2,
 4,
 2,
 2,
 3,
 4,
 6,
 6,
 5,
 2,
 2,
 5,
 2,
 3,
 6,
 2,
 1,
 5,
 2,
 4,
 3,
 0,
 5,
 0,
 5,
 0,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 5,
 3,
 2,
 7,
 7,
 5,
 3,
 2,
 6,
 5,
 2,
 6,
 3,
 2,
 0,
 4,
 1,
 0,
 2,
 5,
 3,
 2,
 4,
 2,
 2,
 2,
 3,
 4,
 3,
 4,
 4,
 0,
 3,
 0,
 0,
 5,
 3,
 3,
 1,
 0,
 2,
 3,
 2,
 2,
 6,
 0,
 6,
 4,
 0,
 2,
 1,
 7,
 0,
 4,
 6,
 5,
 5,
 4,
 4,
 4,
 5,
 0,
 2,
 3,
 0,
 2,
 5,
 2,
 5,
 2,
 4,
 5,
 0,
 2,
 1,
 6,
 6,
 1,
 2,
 2,
 0,
 2,
 0,
 2,
 5,
 0,
 5,
 7,
 2,
 5,
 2,
 1]

In [31]:
len(history_u_lists)

705

In [35]:
social_adj_lists[681]

{27}

In [36]:
ratings_list

{2.0: 0, 1.0: 1, 3.0: 2, 4.0: 3, 2.5: 4, 3.5: 5, 1.5: 6, 0.5: 7}

In [4]:
test_u

[262,
 297,
 477,
 427,
 521,
 88,
 170,
 297,
 552,
 385,
 503,
 696,
 703,
 241,
 588,
 163,
 521,
 76,
 410,
 331,
 53,
 669,
 463,
 385,
 298,
 408,
 173,
 278,
 637,
 493,
 533,
 540,
 257,
 170,
 504,
 81,
 35,
 424,
 69,
 463,
 666,
 146,
 459,
 170,
 218,
 694,
 427,
 36,
 552,
 44,
 213,
 42,
 161,
 619,
 352,
 408,
 666,
 204,
 37,
 401,
 385,
 219,
 1,
 668,
 76,
 367,
 610,
 699,
 252,
 131,
 622,
 534,
 343,
 546,
 529,
 477,
 502,
 331,
 649,
 625,
 631,
 502,
 78,
 410,
 193,
 53,
 235,
 666,
 503,
 646,
 552,
 590,
 568,
 218,
 574,
 669,
 289,
 701,
 693,
 301,
 130,
 219,
 510,
 1,
 600,
 498,
 540,
 410,
 198,
 410,
 430,
 163,
 73,
 358,
 21,
 33,
 74,
 121,
 673,
 360,
 83,
 340,
 90,
 53,
 444,
 549,
 385,
 289,
 637,
 625,
 225,
 484,
 451,
 130,
 151,
 377,
 242,
 367,
 33,
 257,
 696,
 549,
 549,
 171,
 528,
 343,
 321,
 39,
 235,
 520,
 258,
 520,
 187,
 348,
 641,
 625,
 151,
 204,
 225,
 392,
 84,
 348,
 463,
 540,
 516,
 427,
 74,
 669,
 552,
 423,
 281,
 2

In [5]:
test_v

[8,
 24,
 68,
 31,
 65,
 74,
 46,
 8,
 51,
 32,
 11,
 10,
 42,
 78,
 68,
 62,
 57,
 48,
 65,
 93,
 0,
 80,
 26,
 60,
 37,
 68,
 52,
 42,
 6,
 0,
 52,
 32,
 64,
 51,
 78,
 6,
 31,
 69,
 57,
 51,
 0,
 12,
 6,
 76,
 55,
 52,
 78,
 39,
 11,
 31,
 45,
 132,
 51,
 7,
 33,
 24,
 74,
 46,
 8,
 76,
 145,
 34,
 78,
 72,
 95,
 64,
 125,
 57,
 32,
 34,
 102,
 46,
 64,
 31,
 144,
 0,
 26,
 74,
 88,
 80,
 31,
 45,
 33,
 34,
 24,
 79,
 102,
 144,
 64,
 74,
 69,
 46,
 78,
 86,
 45,
 64,
 58,
 69,
 26,
 24,
 6,
 13,
 13,
 62,
 102,
 31,
 125,
 72,
 45,
 145,
 11,
 64,
 21,
 32,
 46,
 39,
 149,
 47,
 37,
 22,
 140,
 125,
 57,
 11,
 47,
 72,
 45,
 20,
 55,
 0,
 159,
 47,
 45,
 11,
 69,
 0,
 10,
 10,
 6,
 145,
 45,
 21,
 80,
 24,
 11,
 46,
 134,
 10,
 39,
 140,
 132,
 80,
 85,
 57,
 45,
 90,
 11,
 64,
 38,
 101,
 21,
 78,
 85,
 144,
 144,
 145,
 132,
 156,
 6,
 22,
 78,
 31,
 42,
 24,
 102,
 33,
 86,
 8,
 58,
 6,
 145,
 52,
 69,
 65,
 74,
 32,
 0,
 11,
 102,
 102,
 93,
 6,
 47,
 13,
 74,
 22,
 45,
 6,
 21

In [7]:
target_users = list(set(test_u))
target_users_items =
candidate_items = list(set(test_v))

In [9]:
len(target_users)

549

In [10]:
len(candidate_items)

355

In [13]:
torch.tensor(np.repeat(23, 4))

tensor([23, 23, 23, 23])

In [18]:
a = np.array([10, 12, 18, 14, 1, 8, 14])
a

array([10, 12, 18, 14,  1,  8, 14])

In [25]:
ind = np.argpartition(a, -4)[-4:]
ind

array([1, 3, 2, 6])

In [20]:
top4 = a[ind]
top4

array([12, 14, 18, 14])

In [28]:
x = ind[np.argsort(a[ind])]

In [31]:
x

array([1, 3, 6, 2])

In [29]:
y = np.flip(x)

In [30]:
y

array([2, 6, 3, 1])

In [33]:
x = [0, 1, 2, 3, 4, 5]
y = [5, 1, 2]
x[]

TypeError: list indices must be integers or slices, not list

In [57]:
target_users_items = pd.DataFrame.from_records(zip(test_u, test_v), columns=['user_id', 'item_id']).groupby('user_id')['item_id'].apply(list).to_dict()

In [58]:
target_users_items

{1: [78, 62, 55, 24, 13],
 3: [45, 72],
 4: [26, 45, 47],
 5: [24, 33, 34],
 6: [0, 13, 102],
 8: [8],
 9: [42, 51, 145, 328, 39, 33, 362],
 10: [47, 88, 62, 0, 45, 76, 69],
 11: [11],
 12: [58, 34, 78, 80, 62, 68],
 13: [34, 80, 63, 86, 38, 502, 410, 26, 122, 119, 62],
 16: [45, 47],
 17: [80],
 21: [46, 22, 85, 62, 86],
 23: [59, 295, 156, 328, 105, 809],
 24: [21, 55, 47, 52, 5, 286, 22, 209],
 25: [32, 337, 45, 26, 140, 42, 22, 214, 156, 31, 88, 52],
 26: [31],
 27: [63, 156, 31],
 28: [264, 13, 52, 42],
 29: [313, 412, 581],
 30: [74],
 31: [122, 33, 85, 51, 64],
 32: [0, 26, 47, 80],
 33: [39, 6, 46, 47, 195],
 34: [24, 57, 144, 45],
 35: [31, 395, 45],
 36: [39,
  52,
  88,
  125,
  57,
  65,
  55,
  20,
  329,
  22,
  144,
  34,
  8,
  32,
  61,
  120,
  80,
  33,
  0],
 37: [8,
  252,
  286,
  32,
  1,
  41,
  73,
  479,
  242,
  5,
  303,
  727,
  385,
  612,
  652,
  370,
  139,
  751,
  304,
  277,
  737,
  187],
 38: [118, 7, 204, 41, 385, 217, 40, 705, 447, 79, 143, 200, 

In [56]:
lal

{1: [78, 62, 55, 24, 13],
 3: [45, 72],
 4: [26, 45, 47],
 5: [24, 33, 34],
 6: [0, 13, 102],
 8: [8],
 9: [42, 51, 145, 328, 39, 33, 362],
 10: [47, 88, 62, 0, 45, 76, 69],
 11: [11],
 12: [58, 34, 78, 80, 62, 68],
 13: [34, 80, 63, 86, 38, 502, 410, 26, 122, 119, 62],
 16: [45, 47],
 17: [80],
 21: [46, 22, 85, 62, 86],
 23: [59, 295, 156, 328, 105, 809],
 24: [21, 55, 47, 52, 5, 286, 22, 209],
 25: [32, 337, 45, 26, 140, 42, 22, 214, 156, 31, 88, 52],
 26: [31],
 27: [63, 156, 31],
 28: [264, 13, 52, 42],
 29: [313, 412, 581],
 30: [74],
 31: [122, 33, 85, 51, 64],
 32: [0, 26, 47, 80],
 33: [39, 6, 46, 47, 195],
 34: [24, 57, 144, 45],
 35: [31, 395, 45],
 36: [39,
  52,
  88,
  125,
  57,
  65,
  55,
  20,
  329,
  22,
  144,
  34,
  8,
  32,
  61,
  120,
  80,
  33,
  0],
 37: [8,
  252,
  286,
  32,
  1,
  41,
  73,
  479,
  242,
  5,
  303,
  727,
  385,
  612,
  652,
  370,
  139,
  751,
  304,
  277,
  737,
  187],
 38: [118, 7, 204, 41, 385, 217, 40, 705, 447, 79, 143, 200, 